package com.threading;

public class ThreadPriorityDemo extends Thread {

	public void run() {
		String threadName = Thread.currentThread().getName();
		
		for(int i=1; i<=2; i++) {
			System.out.println(i+" : generated by, "+threadName);
			try {
				Thread.sleep(2000);
			}
			catch(InterruptedException e) {
				e.printStackTrace();
			}
		}
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		ThreadPriorityDemo demo1= new ThreadPriorityDemo();
		ThreadPriorityDemo demo2= new ThreadPriorityDemo();
		ThreadPriorityDemo demo3= new ThreadPriorityDemo();
		
		//demo1.run();
		demo1.start(); //thread-0
		demo2.start(); //thread-1
		demo3.start(); //thread-2
		demo1.setPriority(10);
		
	}

}
